# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-02 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m', verbose_name='博客标图'),
        ),
    ]
