# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-03 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200702_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='tag',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='tag',
            field=models.ManyToManyField(to='blog.BlogTagModel', verbose_name='标签'),
        ),
    ]
