# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-03 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200703_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='tag',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_type',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='blog.BlogTypeModel', verbose_name='博文分类'),
        ),
    ]
