# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-04 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200703_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtypemodel',
            name='index',
            field=models.SmallIntegerField(default=0, verbose_name='优先级'),
        ),
    ]
